openapi: "3.0.2"
info:
  title: CHILD-TRANSPORTATION-APP
  version: "1.0.0"

components:
  # Authentication using bearer token
  securitySchemes:
    bearerAuth:
      description: "#### Example: Bearer [TOKEN]"
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Register:
      type: object
      properties:
        firstName:
          type: string
          example: tushar
        lastName:
          type: string
          example: parmar
        email:
          type: string
          example: tushar@mailinator.com
        countryCode:
          type: string
          example: "+91"
        phone:
          type: string
          example: 1234567890
        password:
          type: string
          example: abcd@123
        confirmPassword:
          type: string
          example: abcd@123
      required:
        - fullName
        - email
        - countryCode
        - phone
        - password
        - confirmPassword

    Login:
      type: object
      properties:
        email:
          type: string
          format: email
          example: tushar@mailinator.com
        password:
          type: string
          example: abcd@123
      required:
        - email
        - password

  # Response message
  responses:
    Success:
      description: |
        - success
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: success

    UnprocessableEntity:
      description: |
        - Unprocessable Entity
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: validation error

    ConflictError:
      description: |
        - ConflictError
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: conflict error

    BadRequestError:
      description: |
        - bad request error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: bad request error

    UnauthorizedError:
      description: |
        - Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unauthorized

    NotFoundError:
      description: |
        - NotFoundError
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Not Found

paths:
  /auth/send-otp-email:
    post:
      deprecated: true
      summary: OTP send to the Email address
      description: |
        - OTP send email
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: tushar@mailinator.com
              required:
                - email

      responses:
        "200":
          $ref: "#/components/responses/Success"
        "404":
          $ref: "#/components/responses/NotFoundError"